version: '3.8'
services:
  users-service:
    build: .
    ports:
      - "8081:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://admin:admin@ita.8sgnezp.mongodb.net/?retryWrites=true&w=majority&appName=ita
    networks:
      - users-network
    container_name: users-service

networks:
  users-network:
    external: true