version: '3'
services:
  users-service:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:admin@mongo:27017/ita
      - SPRING_DATA_MONGODB_DATABASE=ita
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SERVER_PORT=8081
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ita
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin