version: '3'
services:
  users-service:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://admin:admin@ita.8sgnezp.mongodb.net/?retryWrites=true&w=majority&appName=ita&ssl=true
      - SPRING_DATA_MONGODB_DATABASE=ita
      - SERVER_PORT=8081