version: '3.8'
services:
  users-service:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017/ita?authSource=admin
    networks:
      - users-network
    container_name: users-service

  mongodb:
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      ports: "27018:27017"
      volumes: mongodb_data_container:/data/db
      networks: users-network

volumes:
  mongodb_data_container:

networks:
  users-network:
    external: true