version: '3.8'
services:
  users-service:
    build: .
    ports:
      - "8081:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017/ita?authSource=admin
    networks:
      - users-network
    container_name: users-service

networks:
  users-network:
    external: true